os: linux
dist: focal
language: shell

addons:
  apt:
    packages:
      - bats

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t hra1/iipsrv:latest .

install:
  - docker run  -dit -p 8000:80 hra1/iipsrv:latest

# TODO add actual test execution
script:
  - bats test/*.bats

after_success:
  - docker push hra1/iipsrv:latest
