os: linux
dist: focal
language: shell

addons:
  apt:
    packages:
      - bats

services:
  - docker

install:
  - docker build -t hra1/iipsrv:ci .

before_script:
  - docker run  -dit -p 8000:80 hra1/iipsrv:ci

script:
  - bats test/*.bats

# autobuilds have moved to dockerhub
# deploy:
#   provider: script
#   script: bash docker_push
#   on:
#     branch: master
