os: linux
dist: bionic
language: shell

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# TODO add actual test execution
script:
  - docker build -t hra1/iipsrv:latest .

after_success:
  - docker push hra1/iipsrv:latest
